export { default as Landing } from './Landing'
export { default as About } from './About'
export { default as FAQ } from './FAQ'
export { default as Testimonial } from './Testimonials'
export { default as Team } from './Team'
export { default as Sponsors } from './Sponsors'
